# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weaver_data_provider/v1/genome.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'weaver_data_provider/v1/genome.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from weaver_data_provider.v1 import bundle_pb2 as weaver__data__provider_dot_v1_dot_bundle__pb2
from weaver_data_provider.v1 import store_pb2 as weaver__data__provider_dot_v1_dot_store__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$weaver_data_provider/v1/genome.proto\x12\x17weaver_data_provider.v1\x1a\x1b\x62uf/validate/validate.proto\x1a$weaver_data_provider/v1/bundle.proto\x1a#weaver_data_provider/v1/store.proto\"\x8d\x05\n\x11SequenceCatalogue\x12\x1f\n\x0e\x66ormat_version\x18\x01 \x01(\rB\x07\xbaH\x04*\x02 \x00\x12?\n\x08\x61ssembly\x18\x02 \x01(\x0e\x32!.weaver_data_provider.v1.AssemblyB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00\x12\x43\n\tsequences\x18\x03 \x03(\x0b\x32&.weaver_data_provider.v1.SequenceEntryB\x08\xbaH\x05\x92\x01\x02\x08\x01\x12\x36\n\x06source\x18\x04 \x01(\x0b\x32\x1e.weaver_data_provider.v1.InputB\x06\xbaH\x03\xc8\x01\x01\x12\x18\n\x07\x62uilder\x18\x05 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x1b\n\nblock_size\x18\x06 \x01(\rB\x07\xbaH\x04*\x02 \x00\x12\x33\n\x06\x64igest\x18\x07 \x01(\tB#\xbaH r\x1e\x32\x1c^([0-9a-f]{8}|[0-9a-f]{32})$\x12,\n\x10\x64igest_algorithm\x18\x08 \x01(\tB\x12\xbaH\x0fr\rR\x03md5R\x06\x63rc32c:\xfe\x01\xbaH\xfa\x01\x1a\xf7\x01\n#sequence_catalogue.digest_algorithm\x12Rdigest length must match digest_algorithm: 32 hex characters for md5, 8 for crc32c\x1a|(this.digest_algorithm == \'md5\' && size(this.digest) == 32) || (this.digest_algorithm == \'crc32c\' && size(this.digest) == 8)\"\x84\x01\n\rSequenceEntry\x12\x15\n\x04name\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x17\n\x06length\x18\x02 \x01(\x04\x42\x07\xbaH\x04\x32\x02 \x00\x12.\n\x06\x64igest\x18\x03 \x01(\tB\x1e\xbaH\x1br\x19\x32\x17^SQ\\.[A-Za-z0-9_-]{32}$\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weaver_data_provider.v1.genome_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['format_version']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['format_version']._serialized_options = b'\272H\004*\002 \000'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['assembly']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['assembly']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['sequences']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['sequences']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['source']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['source']._serialized_options = b'\272H\003\310\001\001'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['builder']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['builder']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['block_size']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['block_size']._serialized_options = b'\272H\004*\002 \000'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['digest']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['digest']._serialized_options = b'\272H r\0362\034^([0-9a-f]{8}|[0-9a-f]{32})$'
  _globals['_SEQUENCECATALOGUE'].fields_by_name['digest_algorithm']._loaded_options = None
  _globals['_SEQUENCECATALOGUE'].fields_by_name['digest_algorithm']._serialized_options = b'\272H\017r\rR\003md5R\006crc32c'
  _globals['_SEQUENCECATALOGUE']._loaded_options = None
  _globals['_SEQUENCECATALOGUE']._serialized_options = b'\272H\372\001\032\367\001\n#sequence_catalogue.digest_algorithm\022Rdigest length must match digest_algorithm: 32 hex characters for md5, 8 for crc32c\032|(this.digest_algorithm == \'md5\' && size(this.digest) == 32) || (this.digest_algorithm == \'crc32c\' && size(this.digest) == 8)'
  _globals['_SEQUENCEENTRY'].fields_by_name['name']._loaded_options = None
  _globals['_SEQUENCEENTRY'].fields_by_name['name']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_SEQUENCEENTRY'].fields_by_name['length']._loaded_options = None
  _globals['_SEQUENCEENTRY'].fields_by_name['length']._serialized_options = b'\272H\0042\002 \000'
  _globals['_SEQUENCEENTRY'].fields_by_name['digest']._loaded_options = None
  _globals['_SEQUENCEENTRY'].fields_by_name['digest']._serialized_options = b'\272H\033r\0312\027^SQ\\.[A-Za-z0-9_-]{32}$'
  _globals['_SEQUENCECATALOGUE']._serialized_start=170
  _globals['_SEQUENCECATALOGUE']._serialized_end=823
  _globals['_SEQUENCEENTRY']._serialized_start=826
  _globals['_SEQUENCEENTRY']._serialized_end=958
# @@protoc_insertion_point(module_scope)
