# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weaver_data_provider/v1/index.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'weaver_data_provider/v1/index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from weaver_data_provider.v1 import bundle_pb2 as weaver__data__provider_dot_v1_dot_bundle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#weaver_data_provider/v1/index.proto\x12\x17weaver_data_provider.v1\x1a\x1b\x62uf/validate/validate.proto\x1a$weaver_data_provider/v1/bundle.proto\"\xe6\x02\n\x08KeyTable\x12\x15\n\x04kind\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x0c\n\x04keys\x18\x02 \x01(\x0c\x12\x13\n\x0bkey_offsets\x18\x03 \x01(\x0c\x12\x0f\n\x07records\x18\x04 \x01(\x0c\x12\x16\n\x0erecord_offsets\x18\x05 \x01(\x0c:\xf6\x01\xbaH\xf2\x01\x1a\xef\x01\n\x10keytable.offsets\x12\x64records, key_offsets and record_offsets are uint32 arrays; the two offset arrays are the same length\x1ausize(this.records) % 4 == 0 && size(this.key_offsets) % 4 == 0 && size(this.key_offsets) == size(this.record_offsets)\"\xee\x02\n\x13\x43hromosomeIntervals\x12?\n\x08\x61ssembly\x18\x01 \x01(\x0e\x32!.weaver_data_provider.v1.AssemblyB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00\x12\x1b\n\nchromosome\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\r\n\x05start\x18\x03 \x03(\r\x12\x15\n\rend_inclusive\x18\x04 \x03(\r\x12\x0e\n\x06record\x18\x05 \x03(\r:\xc2\x01\xbaH\xbe\x01\x1a\xbb\x01\n\x12intervals.parallel\x12\x46start, end_inclusive and record are parallel arrays of the same length\x1a]size(this.start) == size(this.end_inclusive) && size(this.end_inclusive) == size(this.record)b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weaver_data_provider.v1.index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYTABLE'].fields_by_name['kind']._loaded_options = None
  _globals['_KEYTABLE'].fields_by_name['kind']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_KEYTABLE']._loaded_options = None
  _globals['_KEYTABLE']._serialized_options = b'\272H\362\001\032\357\001\n\020keytable.offsets\022drecords, key_offsets and record_offsets are uint32 arrays; the two offset arrays are the same length\032usize(this.records) % 4 == 0 && size(this.key_offsets) % 4 == 0 && size(this.key_offsets) == size(this.record_offsets)'
  _globals['_CHROMOSOMEINTERVALS'].fields_by_name['assembly']._loaded_options = None
  _globals['_CHROMOSOMEINTERVALS'].fields_by_name['assembly']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_CHROMOSOMEINTERVALS'].fields_by_name['chromosome']._loaded_options = None
  _globals['_CHROMOSOMEINTERVALS'].fields_by_name['chromosome']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_CHROMOSOMEINTERVALS']._loaded_options = None
  _globals['_CHROMOSOMEINTERVALS']._serialized_options = b'\272H\276\001\032\273\001\n\022intervals.parallel\022Fstart, end_inclusive and record are parallel arrays of the same length\032]size(this.start) == size(this.end_inclusive) && size(this.end_inclusive) == size(this.record)'
  _globals['_KEYTABLE']._serialized_start=132
  _globals['_KEYTABLE']._serialized_end=490
  _globals['_CHROMOSOMEINTERVALS']._serialized_start=493
  _globals['_CHROMOSOMEINTERVALS']._serialized_end=859
# @@protoc_insertion_point(module_scope)
